/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// not @ts-check

const aside_docs = ['Archive']
const category_info = {
  test: {
    description: ' 这里是测试页面的目录'
  }
}

const fs = require('fs');

let category_items = []
let doc_items = []
fs.readdirSync('docs', { withFileTypes: true }).map((dirent, i) => {
  console.log(dirent.name);
  if (i in aside_docs) {
    return
  }
  if (dirent.isDirectory()) {
    let item =
    {
      type: 'category',
      label: dirent.name,
      link: {
        type: 'generated-index',
        title: dirent.name,
        description: category_info?.[dirent.name]?.description ?? ' ',
        slug: dirent.name,
        keywords: [dirent.name],
        image: '/img/docusaurus.png',
      },

      items: [{ type: 'autogenerated', dirName: dirent.name }],
    }

    category_items.push(item)

  } else if (dirent.isFile()) {
    let id = dirent.name.split('.')
    id.pop()
    doc_items.push(id.join('.'))

  }
})


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  archive: [{ type: 'autogenerated', dirName: 'Archive' }],

  docs: [
    ...category_items,
    ...doc_items,
  ]
};


module.exports = sidebars;
